### PR TITLE
add vim input support to codemirror editor

### PR DESCRIPTION
**Pull request by wuguishifu**
I had to raw dog this cuz I couldn't figure out how to set up the dev environment. I copied the existing styles and just put a toggle on the far right. Let me know if you need me to change the style or anything.

### CODE REVIEW

**Comment by enchant97** [comment]
Thanks for working on this so quickly! I will test it as soon as possible. 

Also sorry about the lack of a dev environment, I have not really got around to explaining it in the docs.

**Comment by enchant97** [comment]
I've tested your code, with a few changes I have working version. Will most likely be ready today!

**Comment by wuguishifu** [comment]
Awesome! Can't wait to try it out. Sorry if there were bugs that needed to be fixed, I haven't actually used Solid.js before so I was trying to pattern match some of the code you already had.

**Comment by enchant97** [comment]
I had to adjust how it was initialised, other than that it was working. I ended up changing it further so that it will keep the mode if you change between notes.

After I have finished with the backend rewrite I will start making a better dev environment and document it. Hopefully that will help others in the future!

**Pull request merged**
